import type { IAuditable, ITimeStamps, TEntityId } from '@/types/common'

import type { IUserBase } from '../user'

export interface IMedia extends ITimeStamps, IAuditable {
    id: TEntityId
    file_name: string
    file_size: number
    file_type: string
    storage_key: string
    bucket_name: string
    download_url: string // generated by server not by db
    description?: string
    progress?: number
}

export interface IMediaRequest {
    id?: TEntityId
    file_name: string
    file_size: number
    fileType: string
    storageKey: string
    key?: string
    bucketName?: string

    userId?: TEntityId
    user?: IUserBase
}