/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdentifyFaceRouteImport } from './routes/identify-face'
import { Route as AddFaceRouteImport } from './routes/add-face'
import { Route as IndexRouteImport } from './routes/index'

const IdentifyFaceRoute = IdentifyFaceRouteImport.update({
  id: '/identify-face',
  path: '/identify-face',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFaceRoute = AddFaceRouteImport.update({
  id: '/add-face',
  path: '/add-face',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-face': typeof AddFaceRoute
  '/identify-face': typeof IdentifyFaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-face': typeof AddFaceRoute
  '/identify-face': typeof IdentifyFaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-face': typeof AddFaceRoute
  '/identify-face': typeof IdentifyFaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-face' | '/identify-face'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-face' | '/identify-face'
  id: '__root__' | '/' | '/add-face' | '/identify-face'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFaceRoute: typeof AddFaceRoute
  IdentifyFaceRoute: typeof IdentifyFaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/identify-face': {
      id: '/identify-face'
      path: '/identify-face'
      fullPath: '/identify-face'
      preLoaderRoute: typeof IdentifyFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-face': {
      id: '/add-face'
      path: '/add-face'
      fullPath: '/add-face'
      preLoaderRoute: typeof AddFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFaceRoute: AddFaceRoute,
  IdentifyFaceRoute: IdentifyFaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
